### ISSUE TITLE
A convenient alias idea

### ISSUE THREAD

**Issue by ryuheechul** [sourcegraph/sg.nvim#10]
Very neat plugin!
Maybe mentioning something like this would convince more :)

```bash
# usage: sggh tjdevries/sam.py src/sam.py
# which replaces `nvim sg://github.com/tjdevries/sam.py/-/src/sam.py`

sggh () # sggh: Sourcegraph Github
{
  nvim "sg://github.com/${1}/-/${2}"
}
```

**Comment by tjdevries** [comment]
Nice idea! If you want to put it in here: https://github.com/sourcegraph/sg.nvim/wiki/Convenient-Tooling-and-Scripts that'd be awesome! Thanks :)

**Comment by ryuheechul** [comment]
thanks @tjdevries and I would put this into the wiki but I don't seem to have the access to write into the wiki at the moment.

**Comment by tjdevries** [comment]
Hm, I'm not sure I can give access to non-sg users. I added it as an example! Thanks!
