### ISSUE TITLE
A few QoL suggestions for the searchgraph code search

### ISSUE THREAD

**Issue by chrisgrieser** [sourcegraph/sg.nvim#101]
I've only been using the code search (`require("sg.extensions.telescope").fuzzy_search_results()`) up until now, and it is really awesome to be able to do such a code search without having to leave your editor.

a few small, mostly QoL suggestions for the code search:
- use `vim.ui.input()` to enter the search query. This way, users of UI plugins like [dressing.nvim](https://github.com/stevearc/dressing.nvim) get a nicer UI for entering the search term.
- I think opening one of the search results apparently opens an intermediate buffer before opening the actual buffer? Reason being, I am a heavy user of switching to alt-files (`:b #`), and after opening a searchgraph buffer, `:b #` takes me to the (non-existing) intermediate buffer. I think adding an `:keepalt` could solve this already.
- when searching for a term that has no result, the plugin still opens up an empty telescope window, which I at first mistook for a bug until I realized that I had a typo in my query. It would be better there was a "no results found" notification instead.
```[tasklist]
### Tasks
```

**Comment by tjdevries** [comment]
Sorry, I got covid last week haha so I'm a bit behind. Am still planning on doing these :)

**Comment by tjdevries** [comment]
Actually, think I got all of these! let me know if everything seems fixed for you :)

**Comment by chrisgrieser** [comment]
they still do covid-tests at where you live? Anyway, hope you feel better now!

Also thanks for the implementations, just checked and all three points are fixed! :)
