### ISSUE TITLE
Autocomplete prints filename on each request

### ISSUE THREAD

**Issue by willothy** [sourcegraph/sg.nvim#103]
Just a print statement here, probably not necessary.

https://github.com/sourcegraph/sg.nvim/blob/fb2a7ba26ae56961886d0048879dac30e07aca59/lua/sg/cody/rpc.lua#L269

**Comment by tjdevries** [comment]
Thanks, good call :) Just fixed with 0cc431f5d8f50eaec9fec5e2e6437419a96beff7
