### ISSUE TITLE
error from vim-lsp-rpc thrown on startup

### ISSUE THREAD

**Issue by RussellWaite** [sourcegraph/sg.nvim#113]
When I start Neovim with the sg plugin installed via Lazy I see the following error shown at startup and I can't use Cody:

```
[sg] [INFO  05:25:21] /home/user/data/nvim/lazy/sg.nvim/lua/sg/vendored/vim-lsp-rpc.lua:2
00: client_exit {
[sg]   code = 127,
[sg]   signal = 0
[sg] }
```

Running checkhealth results in
```
sg: require("sg.health").check()

- ERROR Failed to run healthcheck for "sg" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua /home/user/data/nvim/lazy/sg.nvim/lua/sg/health.lua:93: attempt to index local 'info' (a nil value)
  stack traceback:
  /home/user/data/nvim/lazy/sg.nvim/lua/sg/health.lua:93: in function 'report_env'
  /home/user/data/nvim/lazy/sg.nvim/lua/sg/health.lua:151: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

I've stripped back the config to be just Lazy and sg, but the problem persists. I've been running that stripped down config by setting XDG_CONFIG_HOME and XDG_DATA_HOME to different folders than my defaults. Here is the init.lua for the stripped down config:

```lua
-- setup lazy if not already installed
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

-- set any std vim options
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true

-- start using lazy
require("lazy").setup({
	{
        "sourcegraph/sg.nvim",
        dependencies = { "nvim-lua/plenary.nvim" },

        -- If you have a recent version of lazy.nvim, you don't need to add this!
        --build = "nvim -l build/init.lua",
	},
})
```

I use the `SourcegraphLogin` command and enter `https://sourcegraph.com` as the endpoint and then my key, I've even refreshed my key, after the restart the "not logged in" message disappears but the code 127 error is still shown.

I've even tried it with a docker image to see if it's a clashing dependency but that also exhibits the same behavior when only installing arch base-devel, git, node and neovim. 

My OS is Arch Linux, Neovim is version v0.9.2, Node is on version v20.6.0.

Other than the error, Cody never responds (I'm assuming it can't connect to the service). Cody in VSCode is working so I don't think this is a firewall issue (assuming that uses the same address/ports).

I've checked both open and closed issues but none of them seem to match. #7 is not the same, but looks like it was fixed anyway and  #86 was a local install of Sourcegraph whilst I am using the Sourcegraph.com server (I did try http rather than https, it didn't fix it).

I can get more info if required but I'm hitting my knowledge limits of Neovim/Lua so might need to be told how to get that info.

Thanks.

**Comment by RussellWaite** [comment]
I noticed that PR#117 was merged today, so I've updated via Lazy and it's mostly fixed the issue. Cody now responds to requests again. Thank you.

The only issue is the client exit code 127 message is still logged at startup. From my quick tests it doesn't appear to be affecting anything other than logging a message at startup.

**Comment by tjdevries** [comment]
So after the latest update it just tells you that the client has closed (with code 127) but then still responds to your requests?

**Comment by RussellWaite** [comment]
Yes, the error (well, technically a warning) still appears at startup but doesn't stop the Cody functionality from working.

`  Warn  23:19:43 notify.warn Client 1 quit with exit code 127 and signal 0`

This is the output of healthcheck sg now when run in the container after everything has been updated and I've run `:SourcegraphDownloadBinaries` and restarted:

```
sg.nvim report ~
- OK Valid nvim version
- ERROR Unable to find valid cargo executable. Trying to build sg.nvim will fail. Instead use `:Sourcegraph version:DownloadBinaries`
- OK Found `sg-nvim-agent`: /home/user/data/nvim/lazy/sg.nvim/dist/sg-nvim-agent
- OK Found `node` (config.node_executable) is executable
- OK Found `cody-agent`: /home/user/data/nvim/lazy/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables", "nvim", "cody-app" }
- OK   Authentication setup correctly ("nvim")
- OK     endpoint set to: https://sourcegraph.com
- ERROR   Sourcegraph Connection info failed: nil
- ERROR Mismatched cargo and expected version. Update using :SourcegraphDownloadBinaries or :SourcegraphBuild
- ERROR Exptected: 0.2.2 | Found: nil
- ERROR sg.nvim has issues that need to be resolved
```

I still get the last 4 errors in healthcheck when run on my full config, I just don't get the one saying it can't find cargo.

**Comment by tjdevries** [comment]
I've changed the way initialization happens, I'm hopeful this doesn't happen anymore. Let me know!

**Comment by RussellWaite** [comment]
I've upgraded (even requested a re-download of the `:SourcegraphDownloadBinaries`) and I still get a warning, but also Cody has stopped working now.

This is the output from  `:messages` after I start neovim in a folder, pick a file to open and try to submit a question via a new Cody chat:

```
[sg] [INFO  15:38:41] /home/rw/.local/share/nvim/lazy/sg.nvim/lua/sg/vendored/vim-lsp-rpc.lua:200: client_exit {
[sg]   code = 127,
[sg]   signal = 0
[sg] }
E5108: Error executing lua: vim/shared.lua:0: s: expected string, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'gsplit'
	vim/shared.lua: in function 'split'
	...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:134: in function 'callback'
	...rw/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:218: in function 'start'
	...rw/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:206: in function 'chat_question'
	...rw/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/state.lua:84: in function 'request_completion'
	...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:168: in function 'on_submit'
	...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:104: in function 'on_submit'
	...hare/nvim/lazy/sg.nvim/lua/sg/components/cody_prompt.lua:46: in function 'on_submit'
	...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:76: in function <...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:75>
```

I can try to replicate it in the bare bones docker setup I have if you want, it'll be later on today though.

**Comment by RussellWaite** [comment]
I get the same in the minimal version in docker:

```
[sg] [INFO  16:24:18] /home/user/data/nvim/lazy/sg.nvim/lua/sg/vendored/vim-lsp-rpc.lua:200: client_exit {
[sg]   code = 127,
[sg]   signal = 0
[sg] }
E5108: Error executing lua: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...ata/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:134: in function 'callback'
        /home/user/data/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:218: in function 'start'
        /home/user/data/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:206: in function 'chat_question'
        /home/user/data/nvim/lazy/sg.nvim/lua/sg/cody/state.lua:84: in function 'request_completion'
        ...data/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:168: in function 'on_submit'
        ...data/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:104: in function 'on_submit'
        ...data/nvim/lazy/sg.nvim/lua/sg/components/cody_prompt.lua:46: in function 'on_submit'
        ...ata/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:76: in function <...ata/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:75>
```

The `[sg]` messages are from startup, the error is from submitting a question to Cody chat. I went through the login and had to accept the terms before I could use it. I downloaded the binaries via `SourcegraphDownloadBinaries` and restarted when prompted. Not sure if I missed anything.

I forgot to say it before but thanks for looking at this.

**Comment by tjdevries** [comment]
Can you send me the latest checkhealth as well? (and what OS are you on again?)

And no problem :) happy to help and figure out what's wrong!

**Comment by RussellWaite** [comment]
From my dev machine, Arch 6.5.3-arch1-1 (I'll understand if this is the point where you close the ticket, haha) , I get this for the checkhealth sg 

```
sg: require("sg.health").check()

sg.nvim report ~
- OK Valid nvim version
- OK Found `cargo` is executable (can still use `:SourcegraphDownloadBinaries` to avoid building locally)
- OK Found `sg-nvim-agent`: /home/rw/.local/share/nvim/lazy/sg.nvim/dist/sg-nvim-agent
- OK Found `node` (config.node_executable) is executable
- OK Found `cody-agent`: /home/rw/.local/share/nvim/lazy/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables", "nvim", "cody-app" }
- OK   Authentication setup correctly ("nvim")
- OK     endpoint set to: https://sourcegraph.com/
- OK sg.nvim is ready to run

```

In docker (without rust installed) it's just got the one warning about cargo:

```
sg.nvim report ~
- OK Valid nvim version
- WARNING Unable to find valid cargo executable. Trying to build sg.nvim locally will fail. Instead use `:SourcegraphDownloadBinaries`
- OK Found `sg-nvim-agent`: /home/user/data/nvim/lazy/sg.nvim/dist/sg-nvim-agent
- OK Found `node` (config.node_executable) is executable
- OK Found `cody-agent`: /home/user/data/nvim/lazy/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables", "nvim", "cody-app" }
- OK   Authentication setup correctly ("nvim")
- OK     endpoint set to: https://sourcegraph.com
- OK sg.nvim is ready to run
```

I do have the require statement in my dev config, but the docker one doesn't. I even tried adding it to the docker setup but the info message about code 127  still appears on startup and Cody throws the same error as soon as I try to submit a question.

**Comment by tjdevries** [comment]
> Arch 6.5.3-arch1-1 (I'll understand if this is the point where you close the ticket, haha)

LOOOOL

Ok, i'll take a deeper look tomorrow or on Monday again. Thanks for all the info

**Comment by richchurcher** [comment]
Hah. Just piling on, but reproduced on `6.5.5-arch1-1`. Didn't want Russell to be out there on the limb by himself!

**Comment by richchurcher** [comment]
I don't know if this is relevant, but I seem unable to successfully run `:SourcegraphBuild`:
```
Client sourcegraph quit with exit code 127 and signal 0. Check log for errors: /home/basie/.local/state/nvim/lsp.log                                                                                                 
Starting sourcegraph build:                                                                                                                                                                                          
E5112: Error while creating lua chunk: cannot open /home/basie/.local/share/nvim/lazy/sg.nvim/after/build/init.lua: No such file or directory                                                                        
Error executing luv callback:                                                                                                                                                                                        
...basie/.local/share/nvim/lazy/sg.nvim/after/plugin/sg.lua:34: Sourcegraph Build Failed. Check `:messages`                                                                                                          
stack traceback:                                                                                                                                                                                                     
        [C]: in function 'error'                                                                                                                                                                                     
        ...basie/.local/share/nvim/lazy/sg.nvim/after/plugin/sg.lua:34: in function 'on_exit'                                                                                                                        
        /usr/share/nvim/runtime/lua/vim/_system.lua:296: in function </usr/share/nvim/runtime/lua/vim/_system.lua:278>  
```
It's correct: `sg.nvim/after/build` does not exist, though of course `sg.nvim/build` does.

**Comment by richchurcher** [comment]
Aha. So unlike Russell, I had absolutely functional input from Sourcegraph (i.e. nothing worked) and mine was a new install tonight. However,
```shell
$ cd .local/share/nvim/lazy/sg.nvim
$ cargo build --bins
```
made the startup error go away, and at least some features seem to work.

**Comment by RussellWaite** [comment]
Can confirm that if I do this, Cody chat starts working again and I don't see the error at startup (thanks @richchurcher for the workaround)

> Aha. So unlike Russell, I had absolutely functional input from Sourcegraph (i.e. nothing worked) and mine was a new install tonight. However,
> 
> ```shell
> $ cd .local/share/nvim/lazy/sg.nvim
> $ cargo build --bins
> ```
> 
> made the startup error go away, and at least some features seem to work.

**Comment by UTFeight** [comment]
> Aha. So unlike Russell, I had absolutely no functional input from Sourcegraph (i.e. nothing worked) and mine was a new install tonight. However,
> 
> ```shell
> $ cd .local/share/nvim/lazy/sg.nvim
> $ cargo build --bins
> ```
> 
> made the startup error go away, and at least some features seem to work.

I was facing the exact issue, now It's resolved!

**Comment by UTFeight** [comment]
I think you can do something similar in lazy.nvim:

```lua
require("sg").setup {
    build = "cargo build --bins",
}
```

**Comment by psethwick** [comment]
I have a hypothesis:

CPU: AMD
binary in sg.nvim/dist: ELF 64-bit LSB pie executable, x86-64

running `cargo build --bins` builds the correct arch, so that's why that works

Propose changing title of issue to: Wrong binary downloaded for CPU architecture

**Comment by psethwick** [comment]
not working sg-nvim-agent:
```
❯ ldd sg-nvim-agent
	linux-vdso.so.1 (0x00007ffd9e2da000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libgcc_s.so.1 => /nix/store/ryvnrp5n6kqv3fl20qy2xgcgdsza7i0m-xgcc-12.3.0-libgcc/lib/libgcc_s.so.1 (0x00007f904940c000)
	libpthread.so.0 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libpthread.so.0 (0x00007f9049407000)
	libm.so.6 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libm.so.6 (0x00007f9048b20000)
	libdl.so.2 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libdl.so.2 (0x00007f9049400000)
	libc.so.6 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libc.so.6 (0x00007f904893a000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007f904942f000)
```

working sg-nvim-agent:
```
❯ ldd sg-nvim-agent
	linux-vdso.so.1 (0x00007ffc2d0c6000)
	libssl.so.3 => /nix/store/73dswnrd48wncy29ij3b4i71554ap74s-openssl-3.0.9/lib/libssl.so.3 (0x00007f6dab953000)
	libcrypto.so.3 => /nix/store/73dswnrd48wncy29ij3b4i71554ap74s-openssl-3.0.9/lib/libcrypto.so.3 (0x00007f6dab400000)
	libgcc_s.so.1 => /nix/store/v286z87irid5vn13y2z6fphfrzmgj0kf-gcc-12.3.0-lib/lib/libgcc_s.so.1 (0x00007f6dab932000)
	libm.so.6 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libm.so.6 (0x00007f6dab320000)
	libc.so.6 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libc.so.6 (0x00007f6dab13a000)
	/nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/ld-linux-x86-64.so.2 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007f6dacb93000)
	libdl.so.2 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libdl.so.2 (0x00007f6dab92d000)
	libpthread.so.0 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libpthread.so.0 (0x00007f6dab928000)
```

I built the second one with `cargo build --bins`

**Comment by tjdevries** [comment]
Does it work when you use the `:SourcegraphDownloadBinaries` command? 

I think some of the nix stuff might be out-of-date... I wasn't sure how it worked before, so if people are using nix for things that might be the reason it's breaking?

**Comment by psethwick** [comment]
after `:SourcegraphDownloadBinaries`:

```
:messages
[sg] [INFO  08:33:32] /home/seth/.local/share/nvim/lazy/sg.nvim/lua/sg/vendored/vim-lsp-rpc.lua:200: client_exit {
[sg]   code = 127,
[sg]   signal = 0
[sg] }
```

I think this puts them in the plugin /dist folder? `sg-nvim-agent` in that folder has the ldd pathology:
```
❯ ldd dist/sg-nvim-agent
	linux-vdso.so.1 (0x00007ffd5d127000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
<snip>
```

I _do_ use nix for some stuff, but must admit I don't really understand it. Might be worth making a static binary, though? Otherwise your'e in 'package for all linux distros' territory and I bet that'll suck.

**Comment by UTFeight** [comment]
> Aha. So unlike Russell, I had absolutely no functional input from Sourcegraph (i.e. nothing worked) and mine was a new install tonight. However,
> 
> ```shell
> $ cd .local/share/nvim/lazy/sg.nvim
> $ cargo build --bins
> ```
> 
> made the startup error go away, and at least some features seem to work.

You need to use it with the `--release` flag for an optimized build so:

```shell
cd .local/share/nvim/lazy/sg.nvim
cargo build --release --bins
```

**Comment by jamestrew** [comment]
I've had a similar issue before but now everything looks good for far

**Comment by RussellWaite** [comment]
The latest version fixes the issue, no warnings and Cody responds with answers. Thank you for digging into this @tjdevries. 

Would you like me to close the issue or leave it for a bit so others can test also?

**Comment by tjdevries** [comment]
I'll close for now, if anyone has a new issue let's open in separately so that I can track them individually. Thanks so much for everyone's patience as we tracked this down.!
