### ISSUE TITLE
Disable Cody

### ISSUE THREAD

**Issue by sebvilhelm** [sourcegraph/sg.nvim#114]
How do I disable Cody? My employer isn't ready to enable usage of Cody yet, so I'm waiting for that before I can set up Cody, but that means I'm greeted by a ToS prompt every time I open NeoVim. Can I disable the prompt and Cody until I can actually use it?

My current solution is disabling the plugin wholesale, but I'd rather disable the one part.

**Comment by tjdevries** [comment]
Good idea! I added this in the latest commit -- you can call set up with `cody_enable = false` and that should make sure it does not get enabled.
