### ISSUE TITLE
Cody freezes on "loading..."

### ISSUE THREAD

**Issue by Jonathan-79** [sourcegraph/sg.nvim#116]
Hi,
since a couple of days, cody stopped working for me. Every query I try to do any query in it, it results in cody being frozen forever. I tried to debug it, but  couldn't find any errors.
![image](https://github.com/sourcegraph/sg.nvim/assets/69280939/2fb51ae1-5513-44bf-957b-0a1770e1228a)

:checkhealth sg also does not show any errors:
```
sg: require("sg.health").check()

sg.nvim report
- OK Valid nvim version
- OK Found cargo is executable
- OK Found sg-nvim-agent: /home/jon/.nv/plugged/sg.nvim/dist/sg-nvim-agent
- OK Found node (config.node_executable) is executable
- OK Found cody-agent: /home/jon/.nv/plugged/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables" }
- OK   Authentication setup correctly ("environment-variables")
- OK     endpoint set to: https://sourcegraph.com
- OK   Sourcegraph Connection info: {
  access_token_set = true,
  endpoint = "https://sourcegraph.com",
  sg_nvim_version = "0.2.2",
  sourcegraph_version = {
  build = "241514_2023-09-11_5.1-cba1ba6ba79a",
  product = "241514_2023-09-11_5.1-cba1ba6ba79a"
  }
  }
- OK Found correct binary versions: 0.2.2 = 0.2.2
- OK sg.nvim is ready to run

```

I tried to generate a new token, but it does not resolve the issue. my `:messages` output is empty as well.

Do you have any suggestions on how can I debug this issue?

**Comment by jdorfman** [comment]
Hi @Jonathan-79 did you sign up for Sourcegraph before or after August 28th?
