### ISSUE TITLE
cant find binaries on windows

### ISSUE THREAD

**Issue by hornyjailfish** [sourcegraph/sg.nvim#131]
with little investigation files not found because of `.exe` extension
`uv.fs_stat()` in `find_artifact.lua` don't work with filename without extension
https://github.com/sourcegraph/sg.nvim/blob/b0b543285dfefd47eeae93f3f5c812c1dce26ff4/lua/sg/private/find_artifact.lua#L64C5-L64C5

**Comment by tjdevries** [comment]
I think I just fixed this (and hopefully made it so installation works correctly on windows - tested on my windows box).

If you want to give it a go with the latest version, that'd be greatly appreciated!

**Comment by hornyjailfish** [comment]
yes it works now for me

**Comment by tjdevries** [comment]
LETS GOOOOO
