### ISSUE TITLE
Cody not working after the updating the sg.nvim plugin

### ISSUE THREAD

**Issue by Harsh97x** [sourcegraph/sg.nvim#136]
`E5108: Error executing lua: ...user/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:28: attempt to index field 'server_info' (a nil value)
stack traceback:
        ...user/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:28: in function 'is_ready'
        ...user/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:222: in function 'start'
        ...user/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:211: in function 'chat_question'
        .../.local/share/nvim/lazy/sg.nvim/lua/sg/cody/state.lua:84: in function 'request_completion'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:181: in function 'on_submit'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:112: in function 'on_submit'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/cody_prompt.lua:46: in function 'on_submit'
        ...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:78: in function <...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:77>
`

I updated the plugin on 5 Oct. It was working fine before. Now, whenever I open Cody Chat and try to ask something, this error pops out. I am an amateur when it comes to dealing with Lua plugins, so please be kind. Thanks

**Comment by tjdevries** [comment]
Ok, I think I should have fixed this problem in the latest commit -- if it's not fixed, please re-open and i'll try and fix it for you.

Thanks so much for reporting!

(Also, make sure you try `:checkhealth sg` to see if there are any environment problems for you in the plugin)

**Comment by Harsh97x** [comment]
`E5108: Error executing lua: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:136: in function 'callback'
        ...harsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:225: in function 'start'
        ...harsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:213: in function 'chat_question'
        ...rsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/state.lua:84: in function 'request_completion'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:181: in function 'on_submit'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:112: in function 'on_submit'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/cody_prompt.lua:46: in function 'on_submit'
        ...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:78: in function <...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:77>
`

After updating the plugin, Cody still doesn't work. This is the new error pop up.

Also ran `:checkhealth sg` everything was showing OK.
