### ISSUE TITLE
Fix nix build instructions

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/sg.nvim#138]
@willruggiano / @Pegasust 

Do either of you have any thoughts about how to update the nix stuff? I don't think any of it's working but I've also stopped completely changing how we build/setup the environment now. So if you have some thoughts about what could be done I'd love to hear them (otherwise I may try and track it down myself or might just have to remove the nix stuff entirely cause I don't have a good way to test / setup at the moment for it)

Thanks :)

**Comment by willruggiano** [comment]
Dude just get with the Nix c'mon now

**Comment by tjdevries** [comment]
:laughing: it's always on the list, it's just always a little lower than what I have time for @willruggiano

**Comment by willruggiano** [comment]
Don't worry I'll continue to heckle you on stream until you give in :rofl:
