### ISSUE TITLE
Alternative to interactively accepting TOS on startup

### ISSUE THREAD

**Issue by willruggiano** [sourcegraph/sg.nvim#140]
I use Nix to package my neovim environment, and I can't use sg.nvim with the recent-ish Cody integration because the build gets stuck waiting for me to accept TOS, but I can't because it's during the build.

I'd just like an alternative to accepting interactively, e.g. environment variable or global option or something along those lines that can be achieved programatically.

**Comment by tjdevries** [comment]
Ideally it should work if you do `require"sg".setup { accept_tos = true }`, will that work OK for the situation you're saying?

**Comment by willruggiano** [comment]
Perfect! I'll give that a try

**Comment by willruggiano** [comment]
Works like a charm.
