### ISSUE TITLE
Improve onboarding UX

### ISSUE THREAD

**Issue by ryuheechul** [sourcegraph/sg.nvim#141]
_for context, I used sg.nvim before when it moved to sourcegraph org and cody was added_

_At that time I was able to open a file via remote url without logging in_

Now it fails opening it without logging in (seems intended but not stated clearly).

Nonetheless, let's go into a log in process.

Before logging in, when checking the status of logging in, `checkhealth sg` doesn't report the message in a user friendly way but failed to report with the error message like below

```
- ERROR Failed to run healthcheck for "sg" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua /home/user/.local/share/nvim/lazy/sg.nvim/lua/sg/health.lua:76: attempt to call field 'get_info' (a nil value)
  stack traceback:
  /home/user/.local/share/nvim/lazy/sg.nvim/lua/sg/health.lua:76: in function 'report_env'
  /home/user/.local/share/nvim/lazy/sg.nvim/lua/sg/health.lua:158: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

After logging in via `:SourcegraphLogin`, `checkhealth sg` works like below

```
sg.nvim report ~
- OK Valid nvim version
- OK Found `cargo` is executable (can still use `:SourcegraphDownloadBinaries` to avoid building locally)
- OK Found `sg-nvim-agent`: /Users/user/.local/share/nvim/lazy/sg.nvim/dist/sg-nvim-agent
- OK Found `node` (config.node_executable) is executable
- OK Found `cody-agent`: /Users/user/.local/share/nvim/lazy/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables", "nvim", "cody-app" }
- OK   Authentication setup correctly ("nvim")
- OK     endpoint set to: https://sourcegraph.com
- OK   Sourcegraph Connection info: {
  access_token_set = true,
  endpoint = "https://sourcegraph.com",
  sg_nvim_version = "0.2.4",
  sourcegraph_version = {
  build = "245946_2023-10-05_5.2-23290a032166",
  product = "245946_2023-10-05_5.2-23290a032166"
  }
  }
- OK Found correct binary versions: 0.2.4 = 0.2.4
- OK sg.nvim is ready to run
```

_And optionally, it would be great to have a default url, `https://sourcegraph.com` typed in for `:SourcegraphLogin` instead of leaving it empty_

**Comment by tjdevries** [comment]
Hey, thanks for the detailed issue!

I think I've fixed most of the onboarding issues you mentioned (nice suggestions!) in https://github.com/sourcegraph/sg.nvim/pull/142 

Just to confirm the first part you mentioned, you're saying before you were using the Sourcegraph aspects (like opening a file and navigating via `sg://repo/-/path`, but you never logged in? I'm not sure if that should be supported going forward but I can check and see if I can make that work again (it'd be nice to support if possible IMO)

**Comment by ryuheechul** [comment]
You are very welcome and thanks for looking into it!

To answer the question of what happens when you open via, for example, `nvim sg://github.com/tjdevries/sam.py/-/src/sam.py` when I'm not logged in yet result with the error like below (same result with `:edit sg://...`

```bash
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: ...t/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/context.lua:13: attempt to call field 'get_remote_url' (a nil value)
stack traceback:
        ...t/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/context.lua:13: in function 'get_origin'
        .../test/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:261: in function 'initialize'
        .../test/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:143: in function 'start'
        .../test/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:191: in function 'notify'
        .../.local/share/nvim/lazy/sg.nvim/lua/sg/cody/protocol.lua:110: in function 'did_focus'
        ...ocal/share/nvim/lazy/sg.nvim/after/plugin/cody-agent.lua:24: in function <...ocal/share/nvim/lazy/sg.nvim/after/plugin/cody-agent.lua:24>
```

I think it should either:
  - a. be usable without logging in (with limited features) or
  - b. gives better failure and explantion and the guidance on what to do (signing in)

And thanks for the PR #142 to address this issue, I will try the new version when I have a chance and let you know how it went :)

**Comment by tjdevries** [comment]
For now I implemented (at least working for me, in a few different no-auth style items) an error message with instructions on what to do.

If I can dis-entangle some of the server at some point I'll add back viewing Sourcegraph files without logging in if possible, but it will probably be pretty low on the priority list (cause it makes everything more complicated if you're *maybe* logged in haha).

Thanks again, let me know if anything isn't working and I'll try and fix!

**Comment by ryuheechul** [comment]
That's perfect and I can see that it works like a charm now with the new version (on macOS)!

Except that it gets stuck with `Loading...` on Linux on arm machine.

Which I figured out why and created [a new issue](https://github.com/sourcegraph/sg.nvim/issues/154) for that 😄
