### ISSUE TITLE
vim-plug install instructions miss dependency on 'nvim-lua/plenary.nvim'

### ISSUE THREAD

**Issue by alxshine** [sourcegraph/sg.nvim#147]
The installation instructions for vim-plug do not install the necessary plenary.nvim dependency.
This will cause the `:checkhealth sg` command to fail with a somewhat cryptic error mesage.

```
Plug 'nvim-lua/plenary.nvim'
```
Should be added to the Plug install instruction snippet.

**Comment by alxshine** [comment]
Same for 'telescope' for the search functions.

This should probably be mentioned in the README.

**Comment by tjdevries** [comment]
Thanks, good call. I've added some updates. If those don't cover the info you're looking for, let me know and I can add more info!
