### ISSUE TITLE
Errors when Authenticating using "cody-app"

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/sg.nvim#150]
When using `auth_strategy = {"cody-app"}` neovim displays the following error even after verifying that the Cody app is authenticated: 
`[sg-cody] Unable to find valid authentication strategy. See :help sg.auth and then restart nvim`

Additionally, when trying to access `:checkhealth sg ` with the cody-app auth strategy, this error is returned:
```
sg: require("sg.health").check()

- ERROR Failed to run healthcheck for "sg" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua ...utho/.local/share/nvim/plugged/sg.nvim/lua/sg/health.lua:76: attempt to call field 'get_info' (a nil value)
  stack traceback:
  ...utho/.local/share/nvim/plugged/sg.nvim/lua/sg/health.lua:76: in function 'report_env'
  ...utho/.local/share/nvim/plugged/sg.nvim/lua/sg/health.lua:158: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

Steps to Reproduce:
1. Log in to Cody app and authenticate with sourcegraph instance
2. Set auth strategy in config file to _only_ "cody-app"
3. Run neovim
-- "Unble to find valid auth strategy" text should appear
4. Run `:checkhealth sg` and second error should appear

**Comment by morgangauth** [comment]
Discord users experiencing this issue: 
https://discord.com/channels/969688426372825169/1161030235853176862
https://discord.com/channels/969688426372825169/1159196411670315169

**Comment by tjdevries** [comment]
I'm unable to reproduce this locally. Can you double check that you're on the latest sg.nvim plugin and follow the instruction directions (making sure to run the build steps as well?).

If you can still reproduce, can you include the relevant configuration section pasted in as well?

**Comment by tjdevries** [comment]
The new auth method (descriped `:help sg.auth` is to use `:SourcegraphLogin`).
