### ISSUE TITLE
Silent dependency on `openssl`

### ISSUE THREAD

**Issue by alxshine** [sourcegraph/sg.nvim#156]
When missing `libopenssl.so.1.1` the sg-nvim-agent will crash with error code 127.
Finding the root cause is difficult and requires changing the log level to trace to view the full error message.

**Comment by tjdevries** [comment]
Ah! Nice find! So this is why it's been crashing on some other people's systems. Thanks, I will try and figure out how to statically link that or just see if I can get the dep removed somehow.

Thanks!

**Comment by alxshine** [comment]
Alternatively, you can switch the return code to something unique, and produce a meaningful error Message in the nvim Frontend.

Might be less work for now :)

**Comment by tjdevries** [comment]
haha yes, that's also a good option :) thanks a bunch for tracking this down

**Comment by tjdevries** [comment]
So, I might have found something here: https://github.com/sourcegraph/sg.nvim/pull/157, primarily here: https://github.com/sourcegraph/sg.nvim/pull/157/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R42-R43

I'm not sure if it's possible for you to easily confirm that this would fix the problem?

**Comment by alxshine** [comment]
> So, I might have found something here: https://github.com/sourcegraph/sg.nvim/pull/157, primarily here: https://github.com/sourcegraph/sg.nvim/pull/157/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R42-R43
> 
> I'm not sure if it's possible for you to easily confirm that this would fix the problem? 

Nice. I can rebuild with cargo, uninstall the library and try again.

That should answer it, yes?

**Comment by tjdevries** [comment]
yes, when i check after building I get this on my machine:

```
❯ ldd target/debug/sg-nvim-agent
        linux-vdso.so.1 (0x00007ffc261e2000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd9faad6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd9f9519000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd9f9200000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd9fab17000)
```

which seems to indicate we should be good

**Comment by alxshine** [comment]
Okay, I can confirm that building with cargo on the static-ssl branch works, while using the binaries from `:SourcegraphDownload` does not (the library is gone, confirmed with `ldconfig -p | grep openssl`).

*However*, running cargo build on master also works, so I'm not sure what's going on there.

If you want you can send me the executables, and we can hope that the other libraries work?

**Comment by tjdevries** [comment]
Yeah, i can bump the release version to test this out -- i was able to verify locally that without the cargo changes,openssl shows up in ldd, and then after it did not. Either way, that's still a move in the right directoin haha. Let me cut a new release and then when the new artifacts are live, I'll ping in the thread again. Thanks a bunch of the help (would have been very difficult to track this down remotely haha)

**Comment by alxshine** [comment]
Sure thing, I can check again on Friday.

You're very welcome :blush:

**Comment by alxshine** [comment]
Can confirm that this works :partying_face:

**Comment by tjdevries** [comment]
WOO HOO! Thanks so much for your help. Would have spent forever trying to figure this out.
