### ISSUE TITLE
Invalid node configuration, even though the system has valid node version

### ISSUE THREAD

**Issue by dv29** [sourcegraph/sg.nvim#162]
I get the following error when I health check

```
[sg-cody] Invalid node configuration: 'node version must be >= 18.0.0. Got: 1.0.0
```

other information:
System: Linux 6.2.0-34-generic #34~22.04.1-Ubuntu  x86_64
Node: `node -v => v20.5.1`

I've also tried with adding the config for node executable but that doesnt work either, please help on what i can do

**Comment by dv29** [comment]
After some logging, this is whats being returned from the command run

```
1 bash: cannot set terminal process group (-1): Inappropriate ioctl for device
2 bash: no job control in this shell
3 v20.5.1
```

**Comment by tjdevries** [comment]
When you run node from the command line, you get the same output? or that's only output when it's run from within neovim?

Can you send me the results of `:checkhealth sg` as well?

**Comment by dv29** [comment]
It only happens when it runs through vim. 
This is output from terminal bash 
```
11:58 $ node --version
v20.5.1
```

```

==============================================================================
sg: require("sg.health").check()

sg.nvim report ~
- Machine: x86_64, sysname: Linux
- OK Valid nvim version: table: 0x7f206c429448
- OK Found `cargo` (cargo 1.72.1 (103a7ff2e 2023-08-15)) is executable
-     Use `:SourcegraphDownloadBinaries` to avoid building locally.
- OK Found `sg-nvim-agent`: "/home/tyson/.local/share/nvim/site/pack/packer/start/sg.nvim/dist/sg-nvim-agent"
- ERROR Invalid node executable: "node version must be >= 18.0.0. Got: 1.0.0"
- Auth strategy order: { "environment-variables" }
- OK   Authentication setup correctly ("environment-variables")
- OK     endpoint set to: https://sourcegraph.com
- OK   Sourcegraph Connection info: {
  access_token_set = true,
  endpoint = "https://sourcegraph.com",
  sg_nvim_version = "0.2.7",
  sourcegraph_version = {
  build = "247187_2023-10-14_5.2-cf85b5803d32",
  product = "247187_2023-10-14_5.2-cf85b5803d32"
  }
  }
- OK Found correct binary versions: "0.2.7" = "0.2.7"
- ERROR sg.nvim has issues that need to be resolved
```

i'm having a really hard time getting the cody desktop app to work as well because the auth callback to the app is not working. not sure if its because its an appimage or what, so i'm using environment variables.

**Comment by tjdevries** [comment]
Ok, I think latest should work for you (I tested on what looks to be your output and got the expected results now). Let me know if it didn't fix it and I'll be happy to try another fix for you

**Comment by tjdevries** [comment]
No problem :) hope you enjoy the plugin. Let me know if I can fix anything else!
