### ISSUE TITLE
Error after installing sg.nvim: uv_close: Assertion `!uv__is_closing(handle)' failed.

### ISSUE THREAD

**Issue by Kolkhis** [sourcegraph/sg.nvim#169]
Since installing `sg.nvim`, I've had an error when using the command `:wq` - this is not consistent and does not happen every time the command is used.    
This only happens if the file has changed, `:wq` is saving new data to the file, and `:wq` is closing the current Neovim instance - and even then does not happen all the time.
> EDIT: This doesn't seem to be the case. Even if not saving new data, this error can happen.   

Happens randomly with all filetypes.  

Full error:
```bash
"filename.txt" 22L, 793B writtennvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
```
Neovim still exits and sometimes the new data being saved is lost.  

This bug never happens when using `:w` and `:q` separately.  
I wouldn't mind just doing that but my `:wq` muscle memory is too strong.

Since the bug is hard to reproduce and happens at random, it's been very hard to troubleshoot. But this only started happening after installing `sg.nvim`.

I'm running the nightly build of Neovim.  
System is running Ubuntu Server 24.04.3 LTS, x86_64 architecture. 

I will provide any additional information you need from me to troubleshoot.

**Comment by tjdevries** [comment]
Do you currently have Cody set up? Are you getting auto completions for cody via nvim-cmp?

**Comment by Kolkhis** [comment]
> Do you currently have Cody set up? Are you getting auto completions for cody via nvim-cmp?

I do have Cody set up.  
As for auto-completions I'm assuming you mean Cody integration with nvim-cmp, which I do not have set up. I have the basic Cody Ex commands and that's it.

**Comment by Kolkhis** [comment]
After updating with `PackerSync` last week, the issue seems to be resolved.  
I waited to see if it popped up again before closing this issue, but all seems to be working properly now.

**Comment by Kolkhis** [comment]
Sorry to reopen, this issue popped up again after updating Neovim a few days ago.  
I ran `:PackerSync` to check for updates from `sg.nvim` and there were none.  
So it seems nothing has changed except updating Neovim (nightly).  
I logged a few of the errors I got along with the commands I used to close Neovim.  
```error
Sat Dec  9 10:21:35 EST 2023
nvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
Command: :qa!

Sat Dec  9 10:23:56 EST 2023
nvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
Command: :q

Sat Dec  9 12:09:38 EST 2023
"/tmp/bash-fc.zckIlD" 2L, 37B writtennvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
Command: :wq

Sun Dec 10 12:53:14 EST 2023
"main.c" 68L, 1908B writtennvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
Command: :wq

Mon Dec 11 (14:48:02 - 15:08:09) EST 2023
"keybind_cheatsheet.md" 360L, 13828B writtennvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
Command: :wq

nvim: ./.deps/build/src/libuv/src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle)' failed.
Commands: :q :q! :wq :wq! :wqa :qa! :wqa!
```

I was able to replicate the error several times today on primarily markdown files and C files.  
The different states of the file (changed and not written, changed and written, etc) don't seem to be playing a role in what causes the error.  
The error seems to happen more when closing files where I've made smaller edits compared to files in which I've made larger edits.

I uninstalled `sg.nvim` just to be doubly sure that this is what is causing the error, and it stopped after uninstalling.

**Comment by tjdevries** [comment]
What does `:checkhealth sg` show you? I'm wondering if it's something weird with a process not closing all the way before nvim is done. I could possibly try to make sure all of them are shut down before leaving with VimLeavePre or similar if that's the case.

**Comment by Kolkhis** [comment]
> What does `:checkhealth sg` show you? I'm wondering if it's something weird with a process not closing all the way before nvim is done. I could possibly try to make sure all of them are shut down before leaving with VimLeavePre or similar if that's the case.

Says everything is fine. About a week and a half ago I stopped getting the error again. I've only gotten it one time since then, like 3 or 4 days ago (though the same thing happened when I closed this issue the first time, and it came back).

I've set it up for autocompletions since I last posted here.

`:checkhealth sg`:
```checkhealth

==============================================================================
sg: require("sg.health").check()

sg.nvim report ~
- Machine: x86_64, sysname: Linux
- OK Valid nvim version: 0.10.0-dev
- OK Found `cargo` (cargo 1.73.0 (9c4383fb5 2023-08-26)) is executable
-     Use `:SourcegraphDownloadBinaries` to avoid building locally.
- OK Found `sg-nvim-agent`: "/home/kolkhis/.local/share/nvim/site/pack/packer/start/sg.nvim/dist/sg-nvim-agent"
- OK Found `node` (config.node_executable) is executable.
      Version: '20.8.1'
- OK Found `cody-agent`: /home/kolkhis/.local/share/nvim/site/pack/packer/start/sg.nvim/dist/cody-agent.js
- OK   Authentication setup correctly
- OK     endpoint set to: https://sourcegraph.com
- OK Found correct binary versions: "1.0.5" = "1.0.5"
- OK   Sourcegraph Connection info: {
    access_token_set = true,
    endpoint = "https://sourcegraph.com",
    sg_nvim_version = "1.0.5",
    sourcegraph_version = {
      build = "256701_2024-01-05_5.2-2345ed8fc324",
      product = "256701_2024-01-05_5.2-2345ed8fc324"
    }
  }
- To manage your Cody Account, navigate to: https://sourcegraph.com/cody/manage
- OK Cody Account Information: {
 [Redacted cuz I doubt it's needed]
  }
- OK sg.nvim is ready to run
```

**Comment by tjdevries** [comment]
Hmm, ok I'm going to close for now. If you can consistently reproduce again let me know. I'm going to work a bit more on some of the process cleanup anyway at some point, so that may resolve any lingering issues.
