### ISSUE TITLE
Cody completions in nvim version are worse than in vscode

### ISSUE THREAD

**Issue by pmizio** [sourcegraph/sg.nvim#171]
It's probably problem when `cmp` trigger request to cody api not this plugin itself but maybe it's worth to consider solving this problem. Video demonstration:

https://github.com/sourcegraph/sg.nvim/assets/4346598/33f4c776-e352-4051-beaf-e6dc16aa3280

**Comment by tjdevries** [comment]
Are you still getting this behavior? I've updated some of the completion stuff, so it might be better now.

**Comment by KostkaBrukowa** [comment]
Hey. I have similar situation. I'm using enterprise edition of the cody and have same issues. 
One thing I've found is that here https://github.com/sourcegraph/sg.nvim/blob/817f1f36e4c43f82e8e1cdfa4cf978dffa037255/lua/sg/cody/rpc.lua#L305 varialble `remote_url` is nil on every repository I enter. When I manually override this variable 
```
remote_url = 'github.com/company-internal/my-repository-name'
```
completions start to behave like in VSCode. 
Any idea why this variable could be nil and how to fix it?

**Comment by willothy** [comment]
> Are you still getting this behavior? I've updated some of the completion stuff, so it might be better now.

The speed at which autocompletions appear has improved noticeably for me recently.

I am wondering though, can it provide multiline completions? It seems to do so very occasionally but most of the time snippets are truncated at the end of one line.

**Comment by tjdevries** [comment]
I'm going to investigate the multi-line completions next week, it should be able to, but I have been having trouble triggering them consistently in nvim.

**Comment by tjdevries** [comment]
This gap should be much closer now. After #243, they should be exactly the same as vs code. Thanks!
