### ISSUE TITLE
integration with op.nvim

### ISSUE THREAD

**Issue by mrjones2014** [sourcegraph/sg.nvim#174]
Hi! I'm the author of [op.nvim](https://github.com/mrjones2014/op.nvim) and I'm looking for a way to authenticate to Sourcegraph in this plugin via `op.nvim`, which can pull secrets from the 1Password CLI.

Based on a first glance, it doesn't look like there is a great way to do that currently.

I've done similar for the `octo.nvim` plugin, [PR here](https://github.com/pwntester/octo.nvim/pull/346/files), however, based on a cursory look at the code I don't think that approach will work here.

Any thoughts on how we could best approach this in a generic way? All we'd really need is some way for the user to provide a function via config which can dynamically return the token, which can then be implemented by pulling the token from `op.nvim`.

**Comment by mrjones2014** [comment]
Actually, digging into the code a bit more, it looks like the above should work, but I'm getting `Unable to find valid authentication strategy` 🤔 

I'm also getting the Cody ToS prompt with `enable_cody = false` in setup though, so maybe I'm doing something wrong?

**Comment by tjdevries** [comment]
With the latest release I rewrote almost all of the auth stuff. Does setting up the env tokens before running setup work now?

**Comment by mrjones2014** [comment]
It does seem to work now! Although it seems a side effect of `enable_cody = false` is that now I'm getting an error:

`.../share/nvim/lazy/sg.nvim/lua/sg/cody/plugin/commands.lua:211: Invalid command (not found): CodyTaskView`

Although the plugin still functions after that.
