### ISSUE TITLE
Add nv-cmp sources step to installation instructions

### ISSUE THREAD

**Issue by zodoz** [sourcegraph/sg.nvim#190]
Hi all,

I'm setting up nvim + cody for the first time and it took me forever to figure out that the reason I wasn't getting suggestions was because "cody" was not setup as an nvim-cmp source (I'm also new to nvim-cmp). I tried everything else from "sourcegraph" and "sg", but never considered "cody" until I found it from the [source code here](https://github.com/sourcegraph/sg.nvim/blob/2e8f39bc17aee7574a1dae09dc26e3d340c2bd4b/lua/sg/extensions/cmp.lua#L68). It would have saved me multiple hours if this was listed as part of the installation instructions in the [readme](https://github.com/sourcegraph/sg.nvim) and/or on [SourceGraph's site](https://docs.sourcegraph.com/cody/overview/install-neovim).

Hope this can help others, thanks!

**Comment by tjdevries** [comment]
Thanks, I added the info here: 691e138

Good call out :) I had it in the docs for the plugin, but should link in the readme.
