### ISSUE TITLE
Support bun runtime?

### ISSUE THREAD

**Issue by sandangel** [sourcegraph/sg.nvim#199]
Hi, I tried using bunjs instead of nodejs, but got the error that checking nodejs version (>18). Is it possible to bypass that check?

**Comment by tjdevries** [comment]
If you add `skip_node_check = true` in your setup, you should be able to skip this step. Don't know if it will work or not haha but you can let me know :)

**Comment by sandangel** [comment]
Unfortunately it does not work. Cody just loading forever. When I run `bun dist/cody-agent.js` directly it doesn't show any error. Can you share the cody-agent source so I can debug further?

**Comment by sandangel** [comment]
Oh turned out it's working with second try. haha. thanks a lot for supporting this.

**Comment by sandangel** [comment]
hmm, it got stuck again.

<img width="1900" alt="image" src="https://github.com/sourcegraph/sg.nvim/assets/22189661/7c38c42c-455f-4713-9fb6-a3d9cc158985">

**Comment by tjdevries** [comment]
it's possible bun doesn't support all the node APIs that are used in sourcegraph/cody. You could raise an issue in github.com/sourcegraph/cody and see if they'd be willing to fix
