### ISSUE TITLE
Invalid Request

### ISSUE THREAD

**Issue by DieracDelta** [sourcegraph/sg.nvim#20]
On opening any file I searched for from neovim I get the following error from the LSP:
```
Error executing vim.schedule lua callback: ...ovimPackages/start/node-type-nvim/lua/node-type/init.lua:50: RPC[Error] code_name = ParseError, message = "Invalid request\
Method: textDocument/hover\
 error: invalid value: string \"file://sg://github.com/leafgarland/vimfiles@398a5/-/.vimrc\", expected invalid domain character"
stack traceback:
        [C]: in function 'error'
        ...ovimPackages/start/node-type-nvim/lua/node-type/init.lua:50: in function 'handler'
        ...vim-unwrapped-41b7586/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
I'm guessing this might be some weird encoding thing originating from using MacOS instead of Linux.

Version information:
- HEAD of master for `sg.nvim`
- Neovim 0.9.0
- M1 mbp running Ventura (13.3.1)

**Comment by tjdevries** [comment]
Hmm, it shouldn't be preprending `file://` to the hover. I think that's the main problem, I'm not sure why it's happening. Perhaps something has changed in nvim lsp. I can try and check it out in the next week or so.

Does it only happen from search? Or does it also happen if you copy & paste the link and do `:edit ...` ?

**Comment by tjdevries** [comment]
I think this has been fixed now by upstream LSP. Thanks for reporting!
