### ISSUE TITLE
How to install and use it??

### ISSUE THREAD

**Issue by bernardo-zuchowski** [sourcegraph/sg.nvim#21]
Hello,
I am trying to use and access repos via sourcegraph url but when I use the command `:e https://sourcegraph.com/github.com/...` opens a HTML, not the repo that I'm trying to access.

Any one with the same problem... maybe it's fool problem.

**Comment by Vaisakhkm2625** [comment]
Yes, today i tried this, and i am also getting the same result

I am using lazyvim
