### ISSUE TITLE
Switching LLM to ChatGPT 4 Turbo Preview for Cody Pro users

### ISSUE THREAD

**Issue by XenoCode54** [sourcegraph/sg.nvim#210]
I recently just subscribed to Cody Pro, and I've been looking for how to switch to using gpt 4 rather than the default llm available.

How do I switch llm to use Chatgpt 4 turbo preview? 

Any information would be appreciated, thank you!

**Comment by tjdevries** [comment]
I think you should be able to do this with the most recent update now.

If you use `CodyChat` you should see a new window, and when you press `M` in normal mode, it should give you an option to select a different provider. I'm working on figuring out the best way to set default providers

**Comment by sandangel** [comment]
@tjdevries I can not set the model, it still showing anthropic 2.0 as the model. Can you help me with that? I press M and select the model, but there is nothing change after that.

![image](https://github.com/sourcegraph/sg.nvim/assets/22189661/193320a7-ee4c-4ae7-9ff6-899653aad5f5)

**Comment by sandangel** [comment]
![image](https://github.com/sourcegraph/sg.nvim/assets/22189661/f91e21c1-3168-4e71-8fb6-ccacf61c5c77)

**Comment by sandangel** [comment]
hi @tjdevries , can you help me take a look? I just paid sg a month usage to try out, but find out I could not try the new Claude 3 model

**Comment by fadhlirahim** [comment]
Does selecting the Claude3 model also sets the autocompletion?
![Screenshot 2024-03-20 at 1 59 40 PM](https://github.com/sourcegraph/sg.nvim/assets/4056/fe7a92e0-c0dc-4e96-8d1d-790d6e868dbe)

**Comment by tjdevries** [comment]
Sorry, I was away for awhile but have updated sg.nvim and it should have the latest models. You should be able to also set the default model with:

```lua
      require("sg").setup {
        accept_tos = true,
        chat = {
          default_model = "opeanai/gpt-4o",
        },
      }
```

Let me know if that's not working!
