### ISSUE TITLE
Only one model option available for Pro account in CodyChat

### ISSUE THREAD

**Issue by Mihovska** [sourcegraph/sg.nvim#231]
I have the latest update for choosing the model option in CodyChat, but it seems I cannot see the other options but only one. Could you have a look.
I have attached the screenshots for your reference.
![sg_nvim_info](https://github.com/sourcegraph/sg.nvim/assets/5839170/479714df-a00e-44ad-89c2-3fef7a68f54a)
![model_options_nvim](https://github.com/sourcegraph/sg.nvim/assets/5839170/82d3fc28-b041-4c49-b38b-187cc1539920)
![sg_plugin_config_nvim](https://github.com/sourcegraph/sg.nvim/assets/5839170/f8645758-114e-4cd6-b50b-3237c88f2ee9)

**Comment by cloud303-cholden** [comment]
Did you try restarting neovim? The other models showed up for me after I did this.

**Comment by Mihovska** [comment]
> Did you try restarting neovim? The other models showed up for me after I did this.

Yes, I did, but it's still the same.

**Comment by AndreasHnida** [comment]
For me there are 7 models to choose from but it still uses claude 2.0 no matter which one I select. Pro user as well.

**Comment by tjdevries** [comment]
Sorry for the delay, I've updated the underlying extension and you should see all the latest models from cody! (I'm working on adding a way to set the default provider atm)

**Comment by Mihovska** [comment]
I've found a way to manually set up which model to use as the default one. Just set the default model in the config.
These are my settings:

![Screenshot from 2024-06-04 22-33-17](https://github.com/sourcegraph/sg.nvim/assets/5839170/8b85740e-1ec4-4892-883d-7763c6a4d39b)
