### ISSUE TITLE
Support Coc.nvim

### ISSUE THREAD

**Issue by aemonge** [sourcegraph/sg.nvim#238]
Is it possible to support https://github.com/neoclide/coc.nvim ?

**Comment by tjdevries** [comment]
Any chance you could try out: https://github.com/sourcegraph/sg.nvim/pull/242

I tried it locally and it seems to be working for me, but I haven't used coc.nvim in a long time!

**Comment by aemonge** [comment]
I've installed as follows:

```

local M = {
    "sourcegraph/sg.nvim",
    dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-telescope/telescope.nvim",
    },
    branch = "coc-nvim-support",
    -- build = ":SourcegraphDownloadBinaries<CR>"
}
```



But I don't know how to map a manual trigger for completion `<C-a>` or how to start the chat. I don't see any commands named "cody" or "sourgraph" in plugins, nor coc.commands

Issus with health might be versions of nvim ?



```

sg: require("sg.health").check()

sg.nvim report ~
- Machine: x86_64, sysname: Linux
- ERROR Invalid nvim version. Upgrade to at least 0.10.0. Current version: table: 0x7efcbcddfca0
- ERROR Invalid nvim version. Upgrade to at least 0.9.4 or nightly
```



this is my version:

```
 NVIM v0.9.5 
 Build type: Release 
 LuaJIT 2.1.1713773202 
 system vimrc file: "$VIM/sysinit.vim" 
 fall-back for $VIM: "/usr/share/nvim" 
 Run :checkhealth for more info 

```



![1](https://github.com/sourcegraph/sg.nvim/assets/1322348/391badca-ec58-48f5-8c49-4687bf2ba05f)
![1](https://github.com/sourcegraph/sg.nvim/assets/1322348/391badca-ec58-48f5-8c49-4687bf2ba05f)
![2](https://github.com/sourcegraph/sg.nvim/assets/1322348/4ce88f39-9a34-4326-98e0-558a9bf6c248)
![2](https://github.com/sourcegraph/sg.nvim/assets/1322348/4ce88f39-9a34-4326-98e0-558a9bf6c248)
