### ISSUE TITLE
Add support for Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by rmagatti** [sourcegraph/sg.nvim#252]
Given this announcement, it would be great to have support for it in sg.nvim! 🙏 
https://sourcegraph.com/blog/claude-3.5-sonnet-now-available-in-cody

Happy to help make it happen in any way I can as well

**Comment by PavleMrva** [comment]
Hi @rmagatti, if I am not mistaken you can do something like this and it should work:
`
return {
	{
		"sourcegraph/sg.nvim",
		dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
		opts = {
			chat = {
				default_model = "anthropic/claude-3-5-sonnet-20240620",
			},
		},
	},
}
`

**Comment by rmagatti** [comment]
Ah it does work, I suppose it just doesn't show up in the model picker then, should we leave this open until it's added to the picker or is that not intended?

**Comment by PavleMrva** [comment]
I would also expect that all supported models are shown in model picker, but that seems like a different problem, therefore, I would create a separate issue and close this one.
