### ISSUE TITLE
Crash (from Rust panic) on startup if env variables aren't set

### ISSUE THREAD

**Issue by willothy** [sourcegraph/sg.nvim#66]
This has only been affecting me today, not sure what commit I was on before unfortunately. Before today, when the env variables weren't set I would see a warning message and then I could optionally use `SourcegraphLogin`. But now, when I start nvim without the env vars set, nvim shows a Rust panic message for a fraction of a second then crashes. I'll update this with the actual error tomorrow, it disappears very quickly so I'll have to screen record it.

**Comment by tjdevries** [comment]
Nvim should not crash from this -- i know what I did wrong for it, I can send a fix soon.

**Comment by tjdevries** [comment]
Ackshually, does this happen on the very latest one now? I think it should not because we don't have the shared library anymore

**Comment by willothy** [comment]
My bad, forgot about this and didn't post the error haha. I'll update and check right now, will edit this in a few mins
