### ISSUE TITLE
Confusing Cody UI bug when multiple panes open

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sg.nvim#70]
If multiple panes are open, let's say two, and I open Cody with :CodyChat, it opens over the rightmost pane. However, when switching between panes, this can cause confusion, because the cursor will end up navigating to the rightmost pane, which is underneath the CodyChat layer, but the cursor is still visible. It makes for a slightly disorienting UX. 

Disabling navigating to panes Cody is covering when open would be preferable.

https://github.com/sourcegraph/sg.nvim/assets/62355966/05572484-fb78-4c69-890a-8c2e6799747c

**Comment by tjdevries** [comment]
Switched to default view w/ the split, so this should generally fix this problem for people.
