### ISSUE TITLE
Support cancellation in chat

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/sg.nvim#74]

**Comment by pjlast** [comment]
A simple "nuke it all" implementation is here: https://github.com/sourcegraph/sg.nvim/pull/78

From a library/interaction point of view, we should allow cancelling any arbitrary completions that are still running.

But this means we need a way of tracking completions.

Technically they're all tracked by the MessageID UUID, and we could use that, but make it easily usable. We could switch over to using plain old numbers as well.

This would give us a way to cancel specific completions in progress, but how would we use that to cancel the correct completions? Perhaps a layout/history/state keeps of track of the completion callbacks associated with it, and we cancel completions according to that?

**Comment by tjdevries** [comment]
This is handled now I think
