### ISSUE TITLE
Can not find the lib

### ISSUE THREAD

**Issue by meicale** [sourcegraph/sg.nvim#9]
I use packer instead of lazy as my plugin manager. It can not build the plugin build the plugin automatic even I use the “run” option of packer. I have to build the lib manually. Maybe It is better to provide more install and config snips such as using packer. Thx.

**Comment by tjdevries** [comment]
Can you show what you have for packer? I'll try and take a look

**Comment by meicale** [comment]
use {
    "tjdevries/sg.nvim",
    run =  "cargo build --workspace",
    dependencies = { "nvim-lua/plenary.nvim" },
  }
That is the related part of my settiing up about sg.nvim using pakcer. It works fine at this moment NOW! Thanks TJ.

**Comment by meicale** [comment]
I just think this is a cool plugin. 
I am trying to build a portable-DE based on neovim and other command line tools in a container. It will have the ability to use lsp, dap and neotest plugins remotely (in a dev-container or remote server), which is kind of similar with sourcegraph. My GOAL is to separate my development environment(which should be stable) with my project environment(which project depends) and leave my machine neat and clean. What do you think about this? It is said that [neovim will have remote plugin host,](https://neovim.io/roadmap/) Will that be helpful to fullfile my need? Thanks!
