### ISSUE TITLE
Cody chat hangs behind a proxy

### ISSUE THREAD

**Issue by Lattay** [sourcegraph/sg.nvim#96]
I'd like to use sg.nvim behind an HTTP proxy, and currently the chat just hangs.
Usually, that indicates that the component doing the querying does not honor the https_proxy environment variable.
I suppose it is not specific to sg.nvim, but rather to whatever component that does the querying, but since I don't know what is doing what, I prefer to report here.

**Comment by mradspieler** [comment]
Hi Lattay, unfortunately, it doesn't work that way. I tried the following.

modified: sg.nvim/src/lib.rs
```
static CLIENT: Lazy<Client> = Lazy::new(|| {
        let proxy = reqwest::Proxy::all("http://proxy.localhost:1234")
            .expect("Failed to create proxy");
        Client::builder()
            .proxy(proxy)
            .build()
            .expect("Failed to create client")
    });
```
and also in 
lua/sg/request.lua
```
    env = {
      PATH = vim.env.PATH,
      HTTPS_PROXY = "http://proxy.localhost:1234",
      HTTP_PROXY = "http://proxy.localhost:1234",
      http_proxy = "http://proxy.localhost:1234",
      https_proxy = "http://proxy.localhost:1234",
      SRC_ACCESS_TOKEN = vim.env.SRC_ACCESS_TOKEN,
      SRC_ENDPOINT = vim.env.SRC_ENDPOINT,
      SRC_HEADERS = src_headers and vim.json.encode(src_headers) or nil,
    },
  })
```
as far as I can see sg.nvim uses vim.lsp.rpc  to establish connections and unfortunately there is no proxy support. Is that correct? Any tips on how to get sg.nvim to run behind a proxy?

**Comment by Lattay** [comment]
I close this for being outdated, as I can't even get the chat to show now somehow (although the SourcegraphSearch feature works).
